version: "3"

volumes:
  database-design:

services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - database-design:/var/lib/mysql
