version: "3"
volumes:
  mysql_data:
services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=voting_platform
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"